app_VS2022/SimpleWine/SimpleWine/Models/VinhoModel.cs
namespace SimpleWine.Models
{
    public class VinhoModel
    {
        public int Id { get; set; }
        public string Nome { get; set; } = string.Empty;
        public string Origem { get; set; } = string.Empty;
        public string Variedade { get; set; } = string.Empty;
        public string Tipo { get; set; } = string.Empty;
        public int Safra  { get; set; }
        public string? Maturacao { get; set; }
        public string? Graduacaoalcoolica { get; set; }
        public string? Produtor { get; set; }
        public decimal Valor { get; set; }
        public int Promocao { get; set; }

    }
}

app_VS2022/SimpleWine/SimpleWine/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleWine.Services.Vinhos;
using System.Diagnostics;

namespace SimpleWine.Controllers
{
    public class HomeController : Controller
    {
        private readonly IVinhoInterface _vinhoInterface;
        public HomeController(IVinhoInterface vinhoInterface)
        {
            _vinhoInterface = vinhoInterface;            
        }

        public async Task<IActionResult> Index(string? strCriterio,string? Filtro )
        {
            if (strCriterio == null)
            {
                var vinhos = await _vinhoInterface.GetVinhos();
                return View(vinhos);
            } 
            else 
            { 
                var vinhos = await _vinhoInterface.GetVinhosFiltro(strCriterio);
                return View(vinhos);

            }

            return View();
        }

    }
}

app_VS2022/SimpleWine/SimpleWine/Controllers/VinhoController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleWine.Services.Vinhos;

namespace SimpleWine.Controllers
{


    public class VinhoController : Controller
    {
        private readonly IVinhoInterface _vinhosInterface;

        public VinhoController(IVinhoInterface vinhoInterface) {
            _vinhosInterface = vinhoInterface;
        }



        public async Task<IActionResult> Index(string strCriterio)
        {
            var vinhos = await _vinhosInterface.GetVinhos();
            return View(vinhos);
        }
    }
}

app_VS2022/SimpleWine/SimpleWine/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model IEnumerable<VinhoModel>

<div class="py-5">
    <div class="container">
        <div class="text-left mb-5">
            <form method="get" asp-action="index" asp-controller="Home">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-0 justify-content-between">
                    <input name="strCriterio" class="form-control w-50 mx-2" style="border:1px solid black;" placeholder="digite o texto " />
                </div>
            </form>
         </div>


        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-0">

            @if (Model != null)
            {
                @if (Model.Count() > 0)
                {
                    @foreach (var vinho in Model)
                    {
                        <div class="card mx-1 my-1 p-1" style="width: 100rem">
                            <div class="car-body" style="border:1px">
                                <h5> @vinho.Nome</h5>
                                <span>@vinho.Variedade</span>
                                <div class="vinho_linha02" style="border:2px">
                                    <span>@vinho.Origem</span>
                                    <span>@vinho.Safra</span>
                                    <span>@vinho.Tipo</span>
                                    <span>R$ @vinho.Valor</span>
                                </div>
                            </div>
                        </div>

                    }
                }
            }

        </div>

    </div>
</div>

app_VS2022/SimpleWine/SimpleWine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleWine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimpleWine.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>
<body>
    <header style="background-color:purple;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" >
            <div class="container-fluid" style="background-color:purple;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:white;">SimpleWine</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation" style="background-color:purple;">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" style="background-color:purple;">
                    <ul class="navbar-nav flex-grow-1" >
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vinho" asp-action="Index">Vinho</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="form-group">
            @Html.Partial("_rodape")
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SimpleWine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

app_VS2022/SimpleWine/SimpleWine/Views/Shared/_rodape.cshtml
@{
    Layout = null;
}
<form method="get" asp-action="index" asp-controller="Home">
    <div class="text-center" style="background-color:purple">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-6 g-0 justify-content-between" style="padding:10px;">
            <div class="col-2">
                <div> <i class="bi bi-globe-americas" style="color:white" title="região"></i> </div>
            </div>
            <div class="col-2">
                <div> <i class="bi bi-calendar3" style="color:white" title="safra"> </i> </div>
            </div>
            <div class="col-2">
                <div> <i class="bi bi-upc-scan" style="color:white" title="produtor"></i> </div>
            </div>
            <div class="col-2">
                <div> <i class="bi bi-currency-dollar" style="color:white" title="promoções"> </i> </div>
            </div>
            <div class="col-2">
                <div> <i class="bi bi-shadows" style="color:white" title="variedade"></i> </div>
            </div>
            <div class="col-2">
                <div> <i class="bi bi-cart4" style="color:white" title="meu carrinho"></i> </div>
            </div>
        </div>
    </div>
</form>

app_VS2022/SimpleWine/SimpleWine/Views/Vinho/Index.cshtml
@model IEnumerable<VinhoModel>
<div class="py-5">
    <div class="container">
        <div class="text-left ">
            @Html.TextBox("strCriterio") &nbsp;
            <input type="submit" value="Procurar" class="btn btn-default" style="color:white;" /> &nbsp;
            <a class="btn btn-sucess" asp-action="Cadastrar" asp-controller="Vinho" style="color:white;">Novo</a>
        </div>


        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-0">

            @if (Model != null)
            {
                @if (Model.Count() > 0)
                {
                    @foreach (var vinho in Model)
                    {
                        <div class="card mx-1 my-1 p-1" style="width: 100rem">
                            <div class="card-bodyx" style="border:1px">
                                <h5> @vinho.Nome</h5>
                                <span>@vinho.Variedade</span>
                                <div class="vinho_linha02" style="border:2px">
                                    <span>@vinho.Origem</span>
                                    <span>@vinho.Safra</span>
                                    <span>@vinho.Tipo</span>
                                    <span>R$ @vinho.Valor</span>
                                </div>
                            </div>
                        </div>
                        
                    }
                }
            }

        </div>

    </div>
</div>